config/routes.rb
ForgetPasswordApp::Application.routes.draw do
    
    resources :users
  
  root 'static_pages#home'
  match '/faq', to: 'static_pages#help', via: 'get'
  match '/feedback', to: 'static_pages#feedback', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true, format: {with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false }
    validates :NRIC, presence: true
    validates_length_of :NRIC, :minimum => 9, :maximum => 9, :allow_blank => false

    
    
    has_secure_password
    
    validates :password, length: {minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def feedback
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id])
    end
  def new
      @user=User.new
  end
  
  def create
      @user = User.new(user_params)
      if @user.save
          flash[:success] = "Welcome to Commonwealth Secondary School"
          redirect_to @user
      else
        render 'new'
      end
    end
  
  private
  
    def user_params
        params.require(:user).permit(:name, :email, :NRIC, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Commonwealth Secondary School
    </small>
    <p>
        698 West Coast Road Singapore 608784
    </p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <%= link_to "Forget Password", '#', id: "logo"%>    
            <nav>
                <ul class="nav pull-right">
                    <li><%=link_to "Home", root_path%></li>
                    <li><%=link_to "FAQ", faq_path%></li>
                    <li><%=link_to "Feedback", feedback_path%></li>
                    <li><%=link_to "Sign Up", signup_path%></li>
                </ul>
            </nav>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html>
        <head>
            <title> Commonwealth Secondary School | <%= yield(:title)%> </title>
            <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
            <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
            <%= csrf_meta_tags %>
            <%= render 'layouts/shim'%>
        </head>

        <body>
            <%= render 'layouts/header'%>
            <div class="container">
            <% flash.each do |key, value| %>
            <div class="alert alert-<%=key %>"><%=value %></div>
            <% end %>
                <%= yield %>
                <%= render 'layouts/footer'%>
                <%= debug(params) if Rails.env.development? %>
            </div>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id = "error_explanation">
        <div class="alert alert-error">
            The form contains <%pluralize(@user.errors.count, "error")%>
        </div>
        
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%=msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/feedback.html.erb
<%provide(:title, 'Feedback')%>

<h1> Feedback </h1>

<h3> Nothing is perfect... </h3>
            
<p>Appreciate if you could give us your sincere feedback on how we can improve. </p>

app/views/static_pages/help.html.erb
<%provide(:title, 'FAQ')%>

<h1> FAQ </h1>
<p> Below are some of the FAQ asked by students and teachers. </p>

app/views/static_pages/home.html.erb
<%provide(:title, 'Home')%>

<h1> Welcome to 4get Ur Password.</h1>
            
<p> Forget Password? Here is the place you can reset your password. Click on any of the following button to get started. </p>

<center>
    <%=link_to "iMTL", '#' ,class:"btn btn-small btn-primary" %>
    <%=link_to "Google", '#', class:"btn btn-small btn-primary" %>
    <%=link_to "Ask 'N' Learn", '#', class:"btn btn-small btn-primary" %>
    <%=link_to "SSOE", '#', class:"btn btn-small btn-primary" %>
</center>

app/views/users/new.html.erb
<%provide(:title, 'Sign Up')%>

<h1> Sign Up </h1>

<div class = "row">
    <div class="span6 offset3">
        <%=form_for(@user) do |f| %>
        <%=render 'shared/error_messages' %>
            
            <%=f.label :name%>
            <%=f.text_field :name %>
            
            <%=f.label :email%>
            <%=f.text_field :email %>
            
            <%=f.label :NRIC %>
            <%=f.text_field :NRIC %>
            
            <%=f.label :password %>
            <%=f.password_field :password %>
            
            <%=f.label :password_confirmation, "Confirmation"%>
            <%=f.password_field :password_confirmation %>
            
            <%=f.submit "Create my account", class: "btn btn-large btn-primary"%>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>Welcome <%= @user.name %>!</h1>

<p>
Currently, you have the following account. You may request for an account or password reset here. 
</p>

<table>
    <tr>
    <td> Google Account </td>
    <td> <%= @user.google %> </td>
    <td> <%=link_to "Reset Password", '#', class:"btn btn-small btn-primary" %></td>
    </tr>
    
    <tr>
    <td> SSOE Account </td>
    <td> <%= @user.google %> </td>
    <td> <%=link_to "Reset Password", '#', class:"btn btn-small btn-primary" %></td>
    </tr>
    
    <tr>
    <td> Ask N Learn Account </td>
    <td> <%= @user.google %> </td>
    <td> <%=link_to "Request", '#', class:"btn btn-small btn-primary" %></td>
    </tr>
    
    <tr>
    <td> iMTL Account </td>
    <td> <%= @user.google %> </td>
    <td> <%=link_to "Request", '#', class:"btn btn-small btn-primary" %></td>
    </tr>
</table>